<?php

declare(strict_types=1);

namespace BacklinkChecker\Services;

use BacklinkChecker\Database\Database;
use BacklinkChecker\Exceptions\ValidationException;

final class DisavowService
{
    public function __construct(private readonly Database $db)
    {
    }

    public function addRule(int $projectId, int $userId, string $ruleType, string $value, string $reason = ''): int
    {
        $ruleType = strtolower(trim($ruleType));
        if (!in_array($ruleType, ['domain', 'url'], true)) {
            throw new ValidationException('Rule type must be domain or url');
        }

        $value = trim($value);
        if ($value === '') {
            throw new ValidationException('Disavow value is required');
        }

        $existing = $this->db->fetchOne(
            'SELECT id FROM disavow_rules WHERE project_id = ? AND rule_type = ? AND value = ?',
            [$projectId, $ruleType, $value]
        );
        if ($existing !== null) {
            throw new ValidationException('This disavow rule already exists');
        }

        $this->db->execute(
            'INSERT INTO disavow_rules(project_id, rule_type, value, reason, created_by, created_at) VALUES (?, ?, ?, ?, ?, ?)',
            [$projectId, $ruleType, $value, $reason, $userId, gmdate('c')]
        );

        return $this->db->lastInsertId();
    }

    public function removeRule(int $ruleId, int $projectId): void
    {
        $this->db->execute('DELETE FROM disavow_rules WHERE id = ? AND project_id = ?', [$ruleId, $projectId]);
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function listByProject(int $projectId): array
    {
        return $this->db->fetchAll(
            'SELECT * FROM disavow_rules WHERE project_id = ? ORDER BY rule_type ASC, value ASC',
            [$projectId]
        );
    }

    /**
     * Generate Google Disavow Tool compatible text file content.
     */
    public function generateDisavowFile(int $projectId): string
    {
        $rules = $this->listByProject($projectId);
        $lines = ['# Disavow file generated by Backlink Checker Pro v2', '# Date: ' . gmdate('Y-m-d H:i:s') . ' UTC', ''];

        foreach ($rules as $rule) {
            if ($rule['rule_type'] === 'domain') {
                $lines[] = 'domain:' . $rule['value'];
            } else {
                $lines[] = (string) $rule['value'];
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Auto-detect potentially toxic backlinks from scan results and suggest disavow candidates.
     *
     * @return array<int, array<string, mixed>>
     */
    public function suggestFromScan(int $scanId, float $daThreshold = 10.0): array
    {
        return $this->db->fetchAll(
            'SELECT source_url, source_domain, domain_authority, best_link_type '
            . 'FROM scan_results WHERE scan_id = ? AND backlink_found = 1 '
            . 'AND domain_authority IS NOT NULL AND domain_authority < ? '
            . 'ORDER BY domain_authority ASC',
            [$scanId, $daThreshold]
        );
    }
}
